--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/erochow/Nextcloud/Wallpaper/Simple/solarized_paint.png"

-- Special
background="#002B36"
foreground="#93A1A1"
cursor="#268bd2"

-- Colors
color0="#002B36"
color1="#DC322F"
color2="#859900"
color3="#B58900"
color4="#268BD2"
color5="#6C71C4"
color6="#2AA198"
color7="#93A1A1"
color8="#af8700"
color9="#DC322F"
color10="#859900"
color11="#B58900"
color12="#268BD2"
color13="#6C71C4"
color14="#2AA198"
color15="#FDF6E3"
